# Generated by Django 5.2.9 on 2025-12-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which the account is locked.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Count of consecutive failed login attempts.'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Indicates if MFA is active for this user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LEARNER', 'Learner')], default='LEARNER', help_text='User role for RBAC.', max_length=10),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Short string identifier for the action (e.g., 'LOGIN_FAILED').", max_length=50)),
                ('target', models.CharField(blank=True, help_text="Identifier of the object being acted upon (e.g., 'report:123').", max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the event.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the event occurred.')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFASecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField(help_text='Encrypted TOTP secret key.')),
                ('backup_codes_hashed', models.JSONField(help_text='List of hashed backup codes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this MFA secret was generated.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When MFA was last successfully verified.', null=True)),
                ('user', models.OneToOneField(help_text='The user this MFA secret belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mfa_secret', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Secret',
                'verbose_name_plural': 'MFA Secrets',
            },
        ),
    ]
