# Generated by Django 5.2.9 on 2025-12-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_locked_until_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the reset token.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was generated.')),
                ('expires_at', models.DateTimeField(help_text='When the token expires.')),
                ('used', models.BooleanField(default=False, help_text='Whether this token has been used.')),
                ('user', models.ForeignKey(help_text='The user requesting password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
            },
        ),
    ]
