# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_mfa_reset_required'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "accounts_user" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_auditlog" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_mfasecret" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_passwordresettoken" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_user_groups" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_user_user_permissions" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_migrations" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_session" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_admin_log" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_content_type" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "auth_group" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "auth_group_permissions" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "auth_permission" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "otp_totp_totpdevice" ENABLE ROW LEVEL SECURITY;',
            ],
            reverse_sql=[
                'ALTER TABLE "accounts_user" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_auditlog" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_mfasecret" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_passwordresettoken" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_user_groups" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "accounts_user_user_permissions" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_migrations" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_session" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_admin_log" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "django_content_type" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "auth_group" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "auth_group_permissions" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "auth_permission" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "otp_totp_totpdevice" DISABLE ROW LEVEL SECURITY;',
            ]
        ),
    ]
