# Generated by Django 5.2.5 on 2026-08-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_enable_rls_public_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token_version',
            field=models.IntegerField(default=0, help_text='Incremented to instantly invalidate all active JWT tokens for this user.'),
        ),
    ]
