# Generated by Django 5.2.9 on 2025-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='detectionrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
