# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_detectionrun_status_detectionrun_updated_at'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "analysis_analysisfile" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "analysis_detectorresult" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "analysis_detectionrun" ENABLE ROW LEVEL SECURITY;',
            ],
            reverse_sql=[
                'ALTER TABLE "analysis_analysisfile" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "analysis_detectorresult" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "analysis_detectionrun" DISABLE ROW LEVEL SECURITY;',
            ]
        ),
    ]
