# Generated by Django 5.2.5 on 2026-08-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_enable_rls_analysis_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfile',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Stored text or document content for admin inspection', null=True),
        ),
    ]
