# Generated by Django 5.2.9 on 2025-12-28 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or summary.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this content will be hidden from users.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(help_text='Main content (Markdown or HTML).')),
                ('source_name', models.CharField(blank=True, help_text='Original source name if curated.', max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Link to original source.', null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwarenessTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or summary.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this content will be hidden from users.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('teaser', models.TextField(help_text='Short teaser text for the card.')),
                ('icon_name', models.CharField(help_text="Lucide icon name (e.g. 'Brain', 'Lock').", max_length=50)),
                ('color_theme', models.CharField(help_text="CSS gradient class (e.g. 'from-blue-500 to-purple-600').", max_length=50)),
                ('final_action', models.CharField(blank=True, max_length=255, null=True)),
                ('modules', models.JSONField(default=list, help_text='List of learning modules.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or summary.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this content will be hidden from users.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_type', models.CharField(choices=[('DRAG_DROP', 'Drag & Drop'), ('TRUE_FALSE', 'True / False'), ('MULTIPLE_CHOICE', 'Multiple Choice (Quiz Game)'), ('SPOT_BIAS', 'Spot the Bias'), ('MEMORY', 'Memory Match'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('game_data', models.JSONField(help_text='JSON structure defining the game content (questions, terms, scenarios).')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or summary.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this content will be hidden from users.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
