# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "content_article" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "content_awarenesstopic" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "content_game" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "content_quiz" ENABLE ROW LEVEL SECURITY;',
            ],
            reverse_sql=[
                'ALTER TABLE "content_article" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "content_awarenesstopic" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "content_game" DISABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "content_quiz" DISABLE ROW LEVEL SECURITY;',
            ]
        ),
    ]
