# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_enable_rls_content_tables'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE POLICY "Enable read access for all users" ON "content_article" FOR SELECT USING (true);',
                'CREATE POLICY "Enable read access for all users" ON "content_game" FOR SELECT USING (true);',
                'CREATE POLICY "Enable read access for all users" ON "content_quiz" FOR SELECT USING (true);',
                'CREATE POLICY "Enable read access for all users" ON "content_awarenesstopic" FOR SELECT USING (true);',
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "Enable read access for all users" ON "content_article";',
                'DROP POLICY IF EXISTS "Enable read access for all users" ON "content_game";',
                'DROP POLICY IF EXISTS "Enable read access for all users" ON "content_quiz";',
                'DROP POLICY IF EXISTS "Enable read access for all users" ON "content_awarenesstopic";',
            ]
        ),
    ]
