# Generated by Django 5.2.5 on 2026-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_public_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('url_to_image', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAPIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('articles_fetched', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
