# Generated by Django 5.2.5 on 2026-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_enable_rls_news_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachednewsarticle',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='cachednewsarticle',
            name='url_to_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
