# Generated by Django 5.2.5 on 2026-08-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_cachednewsarticle_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachednewsarticle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, hidden from users.'),
        ),
        migrations.AddField(
            model_name='cachednewsarticle',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
    ]
